language: r

warnings_are_errors: true
sudo: required

matrix:
  include:
    - os: linux
      dist: bionic
      r: bioc-devel
    - os: osx
      r: bioc-devel

bioc_check: true
cache: 
  packages: true
